const TopicData = [
  { title: 'JavaScript Basics', screen: 'Document' },
  { title: 'JavaScript Data Types', screen: 'Document' },
  { title: 'JavaScript Objects', screen: 'Document' },
  { title: 'JavaScript Arrays', screen: 'Document' },
  { title: 'JavaScript Functions', screen: 'Document' },
  { title: 'JavaScript Scope', screen: 'Document' },
  { title: 'JavaScript Closures', screen: 'Document' },
  { title: 'JavaScript Promises', screen: 'Document' },
  { title: 'JavaScript Async/Await', screen: 'Document' },
  { title: 'JavaScript DOM Manipulation', screen: 'Document' },
  { title: 'JavaScript Events', screen: 'Document' },
  { title: 'JavaScript Fetch API', screen: 'Document' },
  { title: 'JavaScript LocalStorage', screen: 'Document' },
  { title: 'JavaScript ES6 Features', screen: 'Document' },
  { title: 'JavaScript Modules', screen: 'Document' },
  { title: 'JavaScript Error Handling', screen: 'Document' },
  { title: 'JavaScript Regex', screen: 'Document' },
  { title: 'JavaScript Date & Time', screen: 'Document' },
  { title: 'JavaScript Math', screen: 'Document' },
  { title: 'JavaScript Array Methods', screen: 'Document' },
  { title: 'JavaScript String Methods', screen: 'Document' },
  { title: 'JavaScript Number Methods', screen: 'Document' },
  { title: 'JavaScript Type Coercion', screen: 'Document' },
  { title: 'JavaScript Prototype', screen: 'Document' },
  { title: 'JavaScript Call, Apply, Bind', screen: 'Document' },
  { title: 'JavaScript ES6 Classes', screen: 'Document' },
  { title: 'JavaScript Inheritance', screen: 'Document' },
  { title: 'JavaScript Event Loop', screen: 'Document' },
  { title: 'JavaScript call stack', screen: 'Document' },
  { title: 'JavaScript Tail Recursion', screen: 'Document' },
  { title: 'JavaScript Generators', screen: 'Document' },
  { title: 'JavaScript Iterators', screen: 'Document' },
  { title: 'JavaScript Maps & Sets', screen: 'Document' },
  { title: 'JavaScript WeakMap & WeakSet', screen: 'Document' },
  { title: 'JavaScript Web APIs', screen: 'Document' },
  { title: 'JavaScript JSON', screen: 'Document' },
  { title: 'JavaScript Spread & Rest', screen: 'Document' },
  { title: 'JavaScript Destructuring', screen: 'Document' },
  { title: 'JavaScript Arrow Functions', screen: 'Document' },
  { title: 'JavaScript Callbacks', screen: 'Document' },
  { title: 'JavaScript Memoization', screen: 'Document' },
  { title: 'JavaScript Debounce & Throttle', screen: 'Document' },
  { title: 'JavaScript Networking', screen: 'Document' },
  { title: 'JavaScript CORS', screen: 'Document' },
  { title: 'JavaScript Security Basics', screen: 'Document' },
  { title: 'JavaScript Testing Basics', screen: 'Document' },
  { title: 'JavaScript Performance Tips', screen: 'Document' },
  { title: 'JavaScript Tooling', screen: 'Document' },
  { title: 'JavaScript Build Processes', screen: 'Document' },
]

export default TopicData
